# -*- coding: utf-8 -*-
"""Copy of Ejercicios - Bucles .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hx28mZPfwpKjIigVXFacLWHIsrYigwXS

## FizzBuzz
Escribe un programa que imprima los números del 1 al 100. Pero para los múltiplos de 3, imprime la palabra "Fizz" en lugar del número, y para los múltiplos de 5, imprime "Buzz". Para los números que son múltiplos de tanto 3 como 5, imprime "FizzBuzz".
### Ejemplo de salida:


```
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
...

```
"""

numero = 0
for numero in range(1, 100):
  if numero % 3 == 0:
    print('fizz')
  elif numero % 5 == 0:
    print('Buzz')
  else:
    print(numero)

"""## Sumatoria y promedio
Haz un programa que solicite número al usuario hasta que el usuario ingrese 0, en ese caso el programa tiene que calcular la suma de los números ingresados anteriormente y el promedio
"""

numeros = []
suma = 0

while True:
  numero = int(input('Ingresa un numero, si quieres terminar, ingresa "0": '))
  if numero == 0:
    break
  numeros.append(numero)

suma = sum(numeros)

promedio = suma / len(numeros)
45


print(f'Numeros colocados: {numeros}')
print(f'Suma de numeros ingresados: {suma}')
print(f'Promedio de numeros colocados: {promedio}')

